# Site settings
title: Bithiah
# Site's name
name: Bithiah
author: Bithiah
description: ""
baseurl: ""
url: "https://devargnes.github.io"
exclude: [vendor]
# TODO(max): Use pagefind (pagefind --source . --root-selector .container) but
# avoid scanning _site somehow.
include: [.well-known]

future: false

twitter:
  username: 0xBithiah

permalink: '/blog/:title/'
post_dirs: false

# Build settings
markdown: kramdown
kramdown:
  input: GFM # GitHub Flavored Markdown
  hard_wrap: false
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - rouge

collections:
    blog_lisp:
        output: true
        permalink: /blog/lisp/:path/
    recipes:
        output: true
        permalink: /recipes/:path/

default_og_image: "/favicon.ico"
